import { z } from 'zod';

const playerId = z.string().min(1);
const cardId = z.string().min(1);
const enforcement = z.enum(['word', 'iou', 'written', 'lawyer']);
const dealPreset = z.enum([
  'split_50_50',
  'owner_operator',
  'silent_partner',
  'loan_shark',
  'service_for_equity',
]);

const asset = z.object({
  id: z.string(),
  kind: z.string(),
  name: z.string(),
  tags: z.array(z.string()),
  synergyKeys: z.array(z.string()),
  incomePerRound: z.number(),
  upkeepPerRound: z.number(),
  value: z.number(),
  acquiredRound: z.number(),
  coOwners: z.array(playerId).optional(),
});

const liability = z.object({
  id: z.string(),
  kind: z.enum(['loan', 'margin', 'credit', 'guarantee']),
  principal: z.number(),
  interestRate: z.number(),
  remainingPayments: z.number(),
  creditor: z.string(),
});

const contractTerms = z.object({
  kind: z.enum(['co_ownership', 'loan', 'service', 'partnership', 'guarantee']),
  assetId: z.string().optional(),
  shares: z.record(z.number()).optional(),
  paymentAmount: z.number().optional(),
  paymentInterval: z.number().optional(),
  payerId: playerId.optional(),
  payeeId: playerId.optional(),
  collateral: z.array(z.string()).optional(),
  description: z.string(),
});

const contract = z.object({
  id: z.string(),
  enforcement,
  parties: z.array(playerId),
  terms: contractTerms,
  createdRound: z.number(),
  missedPayments: z.number().min(0).default(0),
  status: z.enum(['active', 'fulfilled', 'breached', 'expired']),
});

const futuresPosition = z.object({
  id: z.string(),
  playerId,
  tokenSymbol: z.string(),
  direction: z.enum(['long', 'short']),
  entryPrice: z.number(),
  quantity: z.number(),
  leverage: z.number(),
  margin: z.number(),
  liquidationPrice: z.number(),
  openedRound: z.number(),
});

const partnership = z.object({
  id: z.string(),
  players: z.array(playerId),
  scope: z.array(z.string()),
  shareRules: z.record(z.number()),
  createdRound: z.number(),
});

const bankDeposit = z.object({
  id: z.string(),
  amount: z.number().positive(),
  rate: z.number().min(0.01).max(0.03),
  openedRound: z.number(),
  lastInterestRound: z.number(),
  lockPeriod: z.number().optional(),
});

const offer = z.object({
  id: z.string().optional(),
  preset: dealPreset.optional(),
  targetPlayerId: playerId,
  assetId: z.string().optional(),
  cashOffer: z.number().optional(),
  cashRequest: z.number().optional(),
  shareSplit: z.record(z.number()).optional(),
  projectedMonthlyIncome: z.number().optional(),
  projectedAssetValue: z.number().optional(),
  enforcement: enforcement.optional(),
  description: z.string(),
});

const pendingDeal = z.object({
  id: z.string(),
  proposerId: playerId,
  targetId: playerId,
  offer,
  status: z.enum(['pending', 'accepted', 'rejected', 'expired']),
  createdRound: z.number(),
  expiresRound: z.number(),
});

const playerState = z.object({
  id: playerId,
  name: z.string(),
  outfit: z.enum(['hustler', 'trader', 'operator', 'nomad', 'creator', 'office']),
  avatarState: z.enum([
    'stable',
    'happy',
    'stressed',
    'overworked',
    'tax_panic',
    'overleveraged',
    'cardboard',
    'passive_calm',
    'futures_liq',
    'nomad',
    'comeback',
    'chaos',
  ]),
  cash: z.number().min(0),
  activeIncome: z.number().min(0),
  passiveIncome: z.number().min(0),
  expenses: z.number().min(0),
  stress: z.number().min(0).max(10),
  trust: z.number().min(0).max(10),
  debt: z.number().min(0).max(10),
  reputation: z.number().min(0).max(10),
  businessSlotsUsed: z.number().min(0),
  businessSlotsMax: z.number().min(0),
  assistantSlotsUsed: z.number().min(0),
  assistantSlotsMax: z.number().min(0),
  businesses: z.array(z.string()),
  assets: z.array(asset),
  liabilities: z.array(liability),
  protections: z.array(z.string()),
  contracts: z.array(contract),
  futuresPositions: z.array(futuresPosition),
  partnerships: z.array(partnership),
  deposits: z.array(bankDeposit),
  pendingDeals: z.array(pendingDeal),
  expenseTags: z.array(z.string()),
  skillTags: z.array(z.string()),
  recapTags: z.array(z.string()),
  housing: z.enum(['renting', 'owned', 'shared', 'cardboard', 'coworking', 'nomad']),
  migrationStatus: z.enum(['settled', 'visa_run', 'digital_nomad', 'exile']),
  kidsCount: z.number().min(0),
  partnerRef: playerId.nullable(),
  pet: z.object({
    id: z.enum(['pet-dog', 'pet-cat', 'pet-gecko', 'pet-fish', 'pet-parrot', 'pet-hamster', 'pet-rabbit', 'pet-turtle']),
    kind: z.enum(['dog', 'cat', 'gecko', 'fish', 'parrot', 'hamster', 'rabbit', 'turtle', 'none']),
    state: z.enum(['happy', 'neutral', 'sad', 'excited']),
  }).nullable(),
  professionId: z.string().optional(),
  taxBand: z.enum(['a', 'b', 'c', 'd']).optional(),
  focusTokens: z.number().min(0).default(2),
  isBot: z.boolean(),
  botPersona: z.enum(['conservative', 'balanced', 'aggressive']).optional(),
  isActive: z.boolean(),
  alive: z.boolean(),
  bankrupt: z.boolean(),
  recentTransfers: z.array(z.object({
    to: playerId,
    amount: z.number(),
    round: z.number(),
  })),
});

const command = z.discriminatedUnion('type', [
  z.object({ type: z.literal('choose_option'), playerId, choiceIndex: z.number().int().min(0) }),
  z.object({ type: z.literal('pass'), playerId }),
  z.object({ type: z.literal('draw_card'), playerId }),
  z.object({ type: z.literal('express_interest'), playerId, targetPlayerId: playerId }),
  z.object({ type: z.literal('close_interest_window'), playerId }),
  z.object({ type: z.literal('submit_offer'), playerId, offer }),
  z.object({ type: z.literal('accept_offer'), playerId, offerId: z.string() }),
  z.object({ type: z.literal('decline_offer'), playerId, offerId: z.string() }),
  z.object({
    type: z.literal('open_futures_position'),
    playerId,
    tokenSymbol: z.string(),
    direction: z.enum(['long', 'short']),
    leverage: z.number().min(1).max(10),
    amount: z.number().positive(),
  }),
  z.object({ type: z.literal('buy_protection'), playerId, protectionId: z.string() }),
  z.object({
    type: z.literal('hire_staff'),
    playerId,
    staffId: z.string(),
    salary: z.number().nonnegative().optional(),
    bonus: z.object({ slots: z.number().optional(), income: z.number().optional() }).optional(),
  }),
  z.object({
    type: z.literal('buy_asset'),
    playerId,
    assetId: z.enum([
      'micro-coffee', 'micro-kiosk', 'micro-studio', 'office', 'coffee',
      'logistics', 'storage', 'ai-startup', 'nft', 'laundromat', 'crypto-mining',
    ]),
  }),
  z.object({
    type: z.literal('buy_pet'),
    playerId,
    petId: z.string(),
  }),
  z.object({ type: z.literal('surrender'), playerId }),
  z.object({ type: z.literal('file_bankruptcy'), playerId }),
  z.object({ type: z.literal('request_help'), playerId, targetPlayerId: playerId.optional() }),
  z.object({ type: z.literal('rent_room'), playerId }),
  z.object({
    type: z.literal('sell_asset'),
    playerId,
    assetId: z.string(),
    salePrice: z.number().positive().optional(),
  }),
  z.object({ type: z.literal('transfer_asset'), playerId, assetId: z.string(), targetPlayerId: playerId }),
  z.object({
    type: z.literal('share_asset'),
    playerId,
    assetId: z.string(),
    targetPlayerId: playerId,
    partnerShare: z.number().positive().max(0.9),
    enforcement: enforcement.optional(),
  }),
  z.object({ type: z.literal('restructure_debt'), playerId, liabilityId: z.string() }),
  z.object({
    type: z.literal('take_survival_job'),
    playerId,
    jobId: z.enum(['gig', 'safe', 'night']),
  }),
  z.object({ type: z.literal('deposit'), playerId, amount: z.number().positive(), lockPeriod: z.number().optional() }),
  z.object({ type: z.literal('withdraw'), playerId, depositId: z.string() }),
  z.object({ type: z.literal('propose_deal'), playerId, targetId: playerId, offer }),
  z.object({ type: z.literal('accept_deal'), playerId, dealId: z.string() }),
  z.object({ type: z.literal('reject_deal'), playerId, dealId: z.string() }),
  z.object({ type: z.literal('take_loan'), playerId, amount: z.number().positive() }),
  z.object({ type: z.literal('repay_loan'), playerId, loanId: z.string() }),
  z.object({
    type: z.literal('submit_draft'),
    playerId,
    peeks: z.array(z.number().int().min(0)),
    claims: z.array(z.object({
      index: z.number().int().min(0),
      blind: z.boolean(),
      contestPref: z.enum(['fight', 'split']),
    })).max(2),
  }),
  z.object({
    type: z.literal('draft_pick_option'),
    playerId,
    index: z.number().int().min(0),
    choiceIndex: z.number().int().min(0),
  }),
]);

const effectType = z.enum([
  'cash.delta',
  'cash.set_zero',
  'cash.loss.reduce',
  'income.add',
  'passive.add',
  'asset.add',
  'asset.remove',
  'liability.add',
  'expense.add',
  'business.slot.modify',
  'assistant.hire',
  'stress.delta',
  'trust.delta',
  'reputation.delta',
  'debt.delta',
  'contract.create',
  'futures.open',
  'futures.resolve',
  'protection.add',
  'market.event.apply',
  'choice.open',
  'deal.window.open',
  'partnership.create',
  'partnership.invoke',
  'partnership.invite',
  'expense.tag',
  'synergy.check',
  'ai_host.cue',
  'reaction.emit',
  'avatar.state.set',
  'pet.state.set',
  'timeline.advance',
  'noop',
  'bankruptcy.file',
  'bankruptcy.review',
  'contract.enforce',
  'contract.breach',
  'macro.policy.apply',
  'election.resolve',
  'job.event.apply',
  'migration.status.set',
  'region.move',
  'internet.reliability.delta',
  'employment.friction.delta',
  'legal.risk.add',
  'liability.restructure',
  'deposit.create',
  'deposit.interest',
  'deposit.withdraw',
  'deal.resolve',
  'synergy.trigger',
  'interest.window.open',
  'interest.window.close',
  'deal.fairness_check',
  'selection.by_focus_tokens',
]);

const gameEvent = z.object({
  type: z.enum([
    'command_accepted',
    'command_rejected',
    'effect',
    'money',
    'host',
    'phase',
    'settlement',
    'finished',
    'warn',
    'contract',
    'futures',
    'deal',
    'timeline',
    'animation',
    'reaction',
    'audit',
  ]),
  playerId: playerId.optional(),
  effectType: effectType.optional(),
  amount: z.number().optional(),
  cue: z.string().optional(),
  message: z.string().optional(),
  round: z.number().optional(),
  payload: z.record(z.unknown()).optional(),
});

const interestWindow = z.object({
  cardId: z.string(),
  cardTitle: z.string(),
  eligiblePlayers: z.array(playerId),
  interestedPlayers: z.array(playerId),
  selectedPlayers: z.array(playerId),
  openedRound: z.number().int().min(1),
  windowDurationMs: z.number().positive(),
  status: z.enum(['open', 'closed']),
});

const volatility = z.object({
  marketEventFrequency: z.number().min(0).max(1),
  eventSeverityMultiplier: z.number().min(0.5).max(2),
  crisisProbability: z.number().min(0).max(1),
  opportunityBonus: z.number().min(0),
});

export const SimulationMatchStateSchema = z.object({
  id: z.string(),
  seed: z.number().int(),
  rngCounter: z.number().int().min(0),
  phase: z.enum([
    'lobby',
    'market_pulse',
    'settlement',
    'decision',
    'intent_window',
    'resolution',
    'deal_window',
    'draft_select',
    'draft_pick',
    'finished',
  ]),
  round: z.number().int().min(1),
  maxRounds: z.number().int().min(1),
  roomMode: z.enum(['calm', 'normal', 'rollercoaster', 'chaos']),
  communicationMode: z.enum(['reactions_only', 'structured_chat']),
  hostMode: z.enum(['silent', 'template', 'llm_text', 'voice', 'video']),
  timer: z.object({
    turnSeconds: z.union([z.literal(45), z.literal(90), z.literal(180)]),
    waitForAllIntents: z.boolean(),
    autoPassOnTimeout: z.boolean(),
  }),
  epoch: z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
    cardPool: z.array(z.string()),
    marketPulseWeights: z.record(z.number()),
    volatility: volatility.optional(),
  }),
  macro: z.object({
    taxRate: z.number().min(0).max(1),
    cryptoPolicy: z.enum(['friendly', 'neutral', 'hostile']),
    employmentFriction: z.number().min(0).max(1),
    migrationCost: z.number().min(0),
    legalProtection: z.number().min(0).max(1),
  }),
  activePlayerIndex: z.number().int().min(0),
  pendingIntents: z.record(command.nullable()),
  players: z.array(playerState).min(2).max(6),
  deck: z.array(cardId),
  deckCursor: z.number().int().min(0),
  discardPile: z.array(cardId),
  currentCardId: cardId.nullable(),
  timeline: z.object({
    year: z.number(),
    month: z.number().min(1).max(12),
    season: z.enum(['spring', 'summer', 'autumn', 'winter']),
    label: z.string(),
  }),
  ticker: z.array(z.string()),
  marketPrices: z.record(z.number()),
  businessMarket: z.object({
    openedRound: z.number().int().min(1),
    nextOpenRound: z.number().int().min(2),
    offerIds: z.array(z.enum([
      'micro-coffee', 'micro-kiosk', 'micro-studio', 'office', 'coffee',
      'logistics', 'storage', 'ai-startup', 'nft', 'laundromat', 'crypto-mining',
    ])).max(3),
  }),
  eventLog: z.array(gameEvent),
  version: z.number().int().min(1),
  activeInterestWindow: interestWindow.nullable().optional(),
  matchMode: z.enum(['classic', 'draft']).optional(),
  autoDeals: z.boolean().optional(),
  draftBoard: z.object({
    cards: z.array(cardId),
    claims: z.record(z.array(z.object({
      index: z.number().int().min(0),
      blind: z.boolean(),
      contestPref: z.enum(['fight', 'split']),
    }))),
    wonBy: z.record(playerId.nullable()),
    picked: z.record(z.boolean()),
    resolved: z.boolean(),
  }).nullable().optional(),
});
