#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, timezone
import subprocess

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
AGENTS = DOCS / "agents"


def git_text(args):
    try:
        return subprocess.check_output(
            ["git", *args],
            cwd=ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return ""


def generate_wikilinks():
    AGENTS.mkdir(parents=True, exist_ok=True)
    files = sorted(
        p for p in list(ROOT.glob("*.md")) + list(DOCS.rglob("*.md")) + list((ROOT / ".planning").rglob("*.md"))
        if ".git" not in p.parts
    )
    lines = [
        "# Agent Wikilinks",
        "",
        "Generated by `tools/agent_autosync.py`.",
        "",
        "## Start Here",
        "",
        "- [[AGENTS|AGENTS]] - `AGENTS.md`",
        "- [[docs/agents/AUTO_CONTEXT|AUTO_CONTEXT]] - `docs/agents/AUTO_CONTEXT.md`",
        "- [[docs/agents/AGENT_START_HERE|AGENT_START_HERE]] - `docs/agents/AGENT_START_HERE.md`",
        "- [[docs/agents/ACTIVE_TASK|ACTIVE_TASK]] - `docs/agents/ACTIVE_TASK.md`",
        "- [[.planning/PROJECT|PROJECT]] - `.planning/PROJECT.md`",
        "- [[.planning/REQUIREMENTS|REQUIREMENTS]] - `.planning/REQUIREMENTS.md`",
        "- [[.planning/ROADMAP|ROADMAP]] - `.planning/ROADMAP.md`",
        "",
        "## All Markdown",
        "",
    ]
    for path in files:
        rel = path.relative_to(ROOT)
        stem = str(rel.with_suffix(""))
        alias = path.stem
        lines.append(f"- [[{stem}|{alias}]] - `{rel}`")
    (AGENTS / "AGENT_WIKILINKS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def generate_auto_context():
    AGENTS.mkdir(parents=True, exist_ok=True)
    now = datetime.now().astimezone()
    status = git_text(["status", "--short"]) or "clean"
    head = git_text(["log", "-1", "--oneline"]) or "no commits yet"
    active = ROOT / "docs/agents/ACTIVE_TASK.md"
    active_text = active.read_text(encoding="utf-8")[:1800] if active.exists() else "(missing)"
    content = f"""# Auto Context

Generated local: {now.isoformat(timespec="seconds")}
Generated UTC: {datetime.now(timezone.utc).isoformat(timespec="seconds")}

## Git

- HEAD: `{head}`
- Status:

```text
{status}
```

## Active Task Excerpt

```markdown
{active_text}
```
"""
    (AGENTS / "AUTO_CONTEXT.md").write_text(content, encoding="utf-8")


if __name__ == "__main__":
    generate_wikilinks()
    generate_auto_context()
    print("Agent autosync complete.")
